### ISSUE TITLE
--cache-from fails if cache does not already exist

### ISSUE THREAD

**Issue by eedwards-sk** [docker/buildx#206]
> could not read /tmp/buildx-cache/index.json: open /tmp/buildx-cache/index.json: no such file or directory

```
  docker buildx build \
    --cache-from type=local,src=/tmp/buildx-cache \
    --cache-to type=local,dest=/tmp/buildx-cache \
    .
```

Is `--cache-from` only supported when the cache already exists? That behavior would make no sense!

What am I missing?

**Comment by tonistiigi** [comment]
this was fixed in https://github.com/moby/buildkit/pull/1285


You can switch to master build with `--driver-opt` if you want to use it now. https://github.com/docker/buildx#--driver-opt-options

**Comment by StiiCeva** [comment]
Tried with the master branch, but the problem persists.

**Comment by Blitz2145** [comment]
I can confirm the problem is still around, here's the command that was run:

```
  mkdir -p ${GITHUB_WORKSPACE}/.buildx
  docker buildx create --driver docker-container --driver-opt image=moby/buildkit:master,network=host --use
  docker buildx build \
    --ssh default \
    -t ${DOCKER_IMAGE} \
    --cache-to=type=local,dest=${GITHUB_WORKSPACE}/.buildx \
    --cache-from=type=local,src=${GITHUB_WORKSPACE}/.buildx \
    --load \
    --file ./Dockerfile .
```

This results in the error `index.json: no such file or directory` on first run when we expect the cache to be empty.

**Comment by tonistiigi** [comment]
@nvpandeti

**Comment by cice** [comment]
Do you have any idea for a workaround?

**Comment by b-jam** [comment]
The reason why it's broken is when you use `--cache-from` and `--cache-to` together, this line fails https://github.com/moby/buildkit/blob/master/client/solve.go#L433
if you run --cache-to on its own first, it will generate the json file and then you can add --cache-from after.

However this workaround is not feasible in e.g. CI/CD multibranch workflows, and should be fixed.

```docker buildx create --driver docker-container --driver-opt image=moby/buildkit:master,network=host --use```

```docker buildx bake```
```could not read .app-docker-cache/index.json: open .app-docker-cache/index.json: no such file or directory```

With docker-bake.hcl containing:
```
group "default" {
  targets = ["app"]
}

target "app" {
  inherits = ["common"]
  args = {
    APP = "app"
  }

  context    = "."
  dockerfile = "docker/app/Dockerfile"
  target     = "app"
  cache-to   = ["type=local,dest=.app-docker-cache"]
  cache-from   = ["type=local,src=.app-docker-cache"]

  output = ["type=docker,name=app"]
}
```

**Comment by tonistiigi** [comment]
@b-jam But the line you are pointing to does not look like a fatal error.

**Comment by b-jam** [comment]
The error itself is ```could not read .app-docker-cache/index.json: open .app-docker-cache/index.json: no such file or directory```

Which I think comes from https://github.com/moby/buildkit/blob/master/client/ociindex/ociindex.go and is called on that line ?

I attempted tracing it back but its possible I'm looking at the wrong part, or not actually running master

**Comment by b-jam** [comment]
So it looks like it is fixed, but it requires buildkit client update in buildx. So using `--driver-opt image=moby/buildkit:master` is not enough

**Comment by Blitz2145** [comment]
I can confirm that this is fixed in master of buildx now. I used buildx:master with the following:
```
          mkdir -p ~/.docker/cli-plugins/
          DOCKER_BUILDKIT=1 docker build --platform=local -o . git://github.com/docker/buildx
          mv buildx ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          mkdir -p /tmp/buildx_image_cache
```
and was able to export and use local cache when building.

**Comment by leolivier** [comment]
Hi
I'm using 
```
$ docker buildx version
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
```
and I still get the same issue...
```
target "front" {
  inherits = ["defaults"]
  context="."
  tags = tag("nginx")
  cache-from = [
    "user/app:cache",
    "type=local,src=/tmp/buildx-cache"
  ]
  cache-to = ["type=local,dest=/tmp/buildx-cache"]
}
```
and when I build, I get:
```
$ docker buildx bake -f ./build.hcl --progress plain --push
[...]
 > importing cache manifest from user/app:cache:
------
------
 > exporting to image:
------
WARNING: local cache import at /tmp/buildx-cache not found due to err: could not read /tmp/buildx-cache/index.json: open /tmp/buildx-cache/index.json: no such file or directory

```

**Comment by epicfaace** [comment]
@b-jam @tonistiigi I just tested this and it's definitely a regression. I tested with buildx v0.8.2 and the error shows up, downgrading to v0.7.0 and it works fine.

**Comment by epicfaace** [comment]
> @b-jam @tonistiigi I just tested this and it's definitely a regression. I tested with buildx v0.8.2 and the error shows up, downgrading to v0.7.0 and it works fine.

Wait, it's also showing up in 0.7.0, never mind... I'll send you a reproduction soon on github

**Comment by epicfaace** [comment]
See https://github.com/epicfaace/ashwin.run/pull/2: -- I get the following warning:

![image](https://user-images.githubusercontent.com/1689183/184732348-f2a15300-2444-4308-b541-988c59fff9d6.png)

**Comment by epicfaace** [comment]
See https://github.com/epicfaace/ashwin.run/pull/2 -- I get this warning:

![image](https://user-images.githubusercontent.com/1689183/184732393-1abac3d8-25d6-4ef2-ac0a-1d6ff14e09bf.png)

**Comment by tonistiigi** [comment]
This is a warning to let you know that nothing was loaded. It does not fail your build.

**Comment by epicfaace** [comment]
Ok, thank you! It sounded like an error but good to know it's not an indicator of anything wrong.
